In [11]:
import os
import zipfile as zf
import pandas as pd
import cvm
pd.set_option("max_colwidth", 10)

In [3]:
df = cvm.load_metadata()
df

         DT_REFER  VERSAO  CD_CVM CATEG_DOC  ID_DOC    DT_RECEB
0      2010-12-31       1    1023       DFP    4822  2011-02-17
1      2010-12-31       2    1023       DFP    4823  2011-02-17
2      2010-12-31       3    1023       DFP    6945  2011-04-30
3      2010-12-31       1   14206       DFP    5436  2011-03-22
4      2010-12-31       2   14206       DFP    6775  2011-04-29
...           ...     ...     ...       ...     ...         ...
34253  2021-09-30       1    4693       ITR  110135  2021-11-16
34254  2021-03-31       1   21091       ITR  103186  2021-04-29
34255  2021-06-30       1   21091       ITR  106768  2021-07-28
34256  2021-09-30       1   21091       ITR  109262  2021-10-27
34257  2022-03-31       1   25810       ITR  110634  2021-12-08

[34258 rows x 6 columns]

In [4]:
files_names = sorted(os.listdir('data/'))
files_names

['dfp_cia_aberta_2010.zip',
 'dfp_cia_aberta_2011.zip',
 'dfp_cia_aberta_2012.zip',
 'dfp_cia_aberta_2013.zip',
 'dfp_cia_aberta_2014.zip',
 'dfp_cia_aberta_2015.zip',
 'dfp_cia_aberta_2016.zip',
 'dfp_cia_aberta_2017.zip',
 'dfp_cia_aberta_2018.zip',
 'dfp_cia_aberta_2019.zip',
 'dfp_cia_aberta_2020.zip',
 'dfp_cia_aberta_2021.zip',
 'itr_cia_aberta_2011.zip',
 'itr_cia_aberta_2012.zip',
 'itr_cia_aberta_2013.zip',
 'itr_cia_aberta_2014.zip',
 'itr_cia_aberta_2015.zip',
 'itr_cia_aberta_2016.zip',
 'itr_cia_aberta_2017.zip',
 'itr_cia_aberta_2018.zip',
 'itr_cia_aberta_2019.zip',
 'itr_cia_aberta_2020.zip',
 'itr_cia_aberta_2021.zip',
 'itr_cia_aberta_2022.zip']

In [12]:
df = pd.DataFrame()
kwargs = {'sep': ';', 'encoding': 'iso-8859-1', 'dtype': str}
for file_name in files_names[0:1]:
    file_path = 'data/' + file_name
    parent_file = zf.ZipFile(file_path)
    # print(parent_file.namelist())
    children_files_names = parent_file.namelist()
    for child_file_name in children_files_names[1:]:
        print(child_file_name)
        child_file = parent_file.open(child_file_name)
        df_child = pd.read_csv(child_file, **kwargs)
        df = pd.concat([df, df_child])
df

dfp_cia_aberta_BPA_con_2010.csv
dfp_cia_aberta_BPA_ind_2010.csv
dfp_cia_aberta_BPP_con_2010.csv
dfp_cia_aberta_BPP_ind_2010.csv
dfp_cia_aberta_DFC_MD_con_2010.csv
dfp_cia_aberta_DFC_MD_ind_2010.csv
dfp_cia_aberta_DFC_MI_con_2010.csv
dfp_cia_aberta_DFC_MI_ind_2010.csv
dfp_cia_aberta_DMPL_con_2010.csv
dfp_cia_aberta_DMPL_ind_2010.csv
dfp_cia_aberta_DRA_con_2010.csv
dfp_cia_aberta_DRA_ind_2010.csv
dfp_cia_aberta_DRE_con_2010.csv
dfp_cia_aberta_DRE_ind_2010.csv
dfp_cia_aberta_DVA_con_2010.csv
dfp_cia_aberta_DVA_ind_2010.csv

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA,DT_INI_EXERC,COLUNA_DF
0,00.000...,2010-1...,3,BCO BR...,001023,DF Con...,REAL,MIL,PENÚLTIMO,2009-1...,1,Ativo ...,702571...,S,NaN,NaN
1,00.000...,2010-1...,3,BCO BR...,001023,DF Con...,REAL,MIL,ÚLTIMO,2010-1...,1,Ativo ...,802819...,S,NaN,NaN
2,00.000...,2010-1...,3,BCO BR...,001023,DF Con...,REAL,MIL,PENÚLTIMO,2009-1...,1.01,Caixa ...,310378...,S,NaN,NaN
3,00.000...,2010-1...,3,BCO BR...,001023,DF Con...,REAL,MIL,ÚLTIMO,2010-1...,1.01,Caixa ...,252197...,S,NaN,NaN
4,00.000...,2010-1...,3,BCO BR...,001023,DF Con...,REAL,MIL,PENÚLTIMO,2009-1...,1.01.01,Caixa ...,809862...,N,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52263,97.837...,2010-1...,2,DURATE...,021091,DF Ind...,REAL,MIL,ÚLTIMO,2010-1...,7.08.0...,Divide...,22878....,S,2010-0...,NaN
52264,97.837...,2010-1...,2,DURATE...,021091,DF Ind...,REAL,MIL,PENÚLTIMO,2009-1...,7.08.0...,Lucros...,112283...,S,2009-0...,NaN
52265,97.837...,2010-1...,2,DURATE...,021091,DF Ind...,REAL,MIL,ÚLTIMO,2010-1...,7.08.0...,Lucros...,312208...,S,2010-0...,NaN
52266,97.837...,2010-1...,2,DURATE...,021091,DF Ind...,REAL,MIL,PENÚLTIMO,2009-1...,7.08.05,Outros,0.0000...,S,2009-0...,NaN
52267,97.837...,2010-1...,2,DURATE...,021091,DF Ind...,REAL,MIL,ÚLTIMO,2010-1...,7.08.05,Outros,0.0000...,S,2010-0...,NaN