In [1]:
import importlib
import pandas as pd
import numpy as np
import context # noqa
import brfinance.dataset as bf
importlib.reload(bf)
pd.options.display.max_colwidth = 50
pd.options.display.max_rows = 40

In [2]:
file_path = '/home/crcj/GitHub/BrFin/brfinance/data/processed/dataset.pkl.zst'
DATASET = pd.read_pickle(file_path)
DATASET

,corp_name,corp_cvm_id,corp_fiscal_id,report_type,report_version,period_reference,period_begin,period_end,period_order,account_code,account_name,accounting_method,account_fixed,account_value,equity_statement_column
0,PANATLANTICA S.A.,94,92.693.019/0001-89,annual,2,2010-12-31,NaT,2009-12-31,-1,1,Ativo Total,consolidated,True,211293000.0,NaN
1,PANATLANTICA S.A.,94,92.693.019/0001-89,annual,2,2010-12-31,NaT,2009-12-31,-1,1.01,Ativo Circulante,consolidated,True,164307000.0,NaN
2,PANATLANTICA S.A.,94,92.693.019/0001-89,annual,2,2010-12-31,NaT,2009-12-31,-1,1.01.01,Caixa e Equivalentes de Caixa,consolidated,True,2055000.0,NaN
3,PANATLANTICA S.A.,94,92.693.019/0001-89,annual,2,2010-12-31,NaT,2009-12-31,-1,1.01.02,Aplicações Financeiras,consolidated,True,44510000.0,NaN
4,PANATLANTICA S.A.,94,92.693.019/0001-89,annual,2,2010-12-31,NaT,2009-12-31,-1,1.01.02.02,Aplicações Financeiras Avaliadas ao Custo Amor...,consolidated,True,44510000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6915498,BRAMEX - BRASIL MERCANTIL S.A.,518700,70.216.429/0001-04,annual,1,2013-12-31,2013-01-01,2013-12-31,0,7.08.03,Remuneração de Capitais de Terceiros,separate,True,328371.0,NaN
6915499,BRAMEX - BRASIL MERCANTIL S.A.,518700,70.216.429/0001-04,annual,1,2013-12-31,2013-01-01,2013-12-31,0,7.08.03.01,Juros,separate,True,328371.0,NaN
6915500,BRAMEX - BRASIL MERCANTIL S.A.,518700,70.216.429/0001-04,annual,1,2013-12-31,2013-01-01,2013-12-31,0,7.08.04,Remuneração de Capitais Próprios,separate,True,-1200611.0,NaN
6915501,BRAMEX - BRASIL MERCANTIL S.A.,518700,70.216.429/0001-04,annual,1,2013-12-31,2013-01-01,2013-12-31,0,7.08.04.03,Lucros Retidos / Prejuízo do Período,separate,True,-1200611.0,NaN
6915502,BRAMEX - BRASIL MERCANTIL S.A.,518700,70.216.429/0001-04,annual,1,2013-12-31,2013-01-01,2013-12-31,0,7.08.05,Outros,separate,True,486752.0,NaN

In [5]:
DATASET.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6915503 entries, 0 to 6915502
Data columns (total 15 columns):
 #   Column                   Dtype
---  ------                   -----
 0   corp_name                category
 1   corp_id                  category
 2   corp_fiscal_id           category
 3   report_type              category
 4   report_version           category
 5   period_reference         category
 6   period_begin             category
 7   period_end               category
 8   period_order             category
 9   account_code             category
 10  account_name             category
 11  accounting_method        category
 12  account_fixed            category
 13  account_value            category
 14  equity_statement_column  category
dtypes: category(15)
memory usage: 214.2 MB

In [3]:
DATASET.columns

Index(['corp_name', 'corp_cvm_id', 'corp_fiscal_id', 'report_type',
       'report_version', 'period_reference', 'period_begin', 'period_end',
       'period_order', 'account_code', 'account_name', 'accounting_method',
       'account_fixed', 'account_value', 'equity_statement_column'],
      dtype='object')

In [6]:
# DATASET.query('report_type == "quarterly"')
len(DATASET.drop_duplicates(subset=['corp_cvm_id', 'report_version', 'report_type', 'period_reference']).index)

11628

In [10]:
df = DATASET.query(
    'cvm_id == 20036 and report_type == "annual" and period_reference == "2021-06-30"'
    ).copy()
# df_dataset.query("VL_CONTA == 0")
df

,cvm_id,fiscal_id,company_name,report_type,report_version,period_reference,period_begin,period_end,period_order,account_code,account_name,account_basis,account_fixed,account_value,equity_statement_column
3555247,20036,07.628.528/0001-59,BRASILAGRO - CIA BRAS DE PROP AGRICOLAS,annual,1,2021-06-30,NaT,2020-06-30,-1,1,Ativo Total,consolidated,True,2.044368e+09,NaN
3555248,20036,07.628.528/0001-59,BRASILAGRO - CIA BRAS DE PROP AGRICOLAS,annual,1,2021-06-30,NaT,2020-06-30,-1,1.01,Ativo Circulante,consolidated,True,6.424640e+08,NaN
3555249,20036,07.628.528/0001-59,BRASILAGRO - CIA BRAS DE PROP AGRICOLAS,annual,1,2021-06-30,NaT,2020-06-30,-1,1.01.01,Caixa e Equivalentes de Caixa,consolidated,True,1.710450e+08,NaN
3555250,20036,07.628.528/0001-59,BRASILAGRO - CIA BRAS DE PROP AGRICOLAS,annual,1,2021-06-30,NaT,2020-06-30,-1,1.01.03,Contas a Receber,consolidated,True,1.840510e+08,NaN
3555251,20036,07.628.528/0001-59,BRASILAGRO - CIA BRAS DE PROP AGRICOLAS,annual,1,2021-06-30,NaT,2020-06-30,-1,1.01.03.02,Outras Contas a Receber,consolidated,True,1.840510e+08,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3556169,20036,07.628.528/0001-59,BRASILAGRO - CIA BRAS DE PROP AGRICOLAS,annual,1,2021-06-30,2020-07-01,2021-06-30,0,7.08.03.03.01,Despesas financeiras,separate,False,7.845300e+08,NaN
3556170,20036,07.628.528/0001-59,BRASILAGRO - CIA BRAS DE PROP AGRICOLAS,annual,1,2021-06-30,2020-07-01,2021-06-30,0,7.08.04,Remuneração de Capitais Próprios,separate,True,2.422050e+08,NaN
3556171,20036,07.628.528/0001-59,BRASILAGRO - CIA BRAS DE PROP AGRICOLAS,annual,1,2021-06-30,2020-07-01,2021-06-30,0,7.08.04.03,Lucros Retidos / Prejuízo do Período,separate,True,2.422050e+08,NaN
3556172,20036,07.628.528/0001-59,BRASILAGRO - CIA BRAS DE PROP AGRICOLAS,annual,1,2021-06-30,2020-07-01,2021-06-30,0,7.08.05,Outros,separate,True,7.544100e+07,NaN
3556173,20036,07.628.528/0001-59,BRASILAGRO - CIA BRAS DE PROP AGRICOLAS,annual,1,2021-06-30,2020-07-01,2021-06-30,0,7.08.05.01,Dividendos mínimos obrigatórios,separate,False,7.544100e+07,NaN

In [38]:
df['account_codes_1and2'] = df['CD_CONTA'].str[0:4]
df.query('account_codes_1and2 == "3.99" and DT_FIM_EXERC == "2021-12-31"')

,CD_CVM,CNPJ_CIA,DENOM_CIA,report_period,report_type,DT_REFER,VERSAO,DT_INI_EXERC,DT_FIM_EXERC,ORDEM_EXERC,CD_CONTA,DS_CONTA,ST_CONTA_FIXA,COLUNA_DF,VL_CONTA,account_codes_1and2
6361992,25291,12.091.809/...,3R PETROLEU...,annual,consolidated,2021-12-31,1,2021-01-01,2021-12-31,0,3.99.01.01,ON,False,NaN,-0.01,3.99
6361993,25291,12.091.809/...,3R PETROLEU...,annual,consolidated,2021-12-31,1,2021-01-01,2021-12-31,0,3.99.02.01,ON,False,NaN,-0.01,3.99
6362212,25291,12.091.809/...,3R PETROLEU...,annual,separate,2021-12-31,1,2021-01-01,2021-12-31,0,3.99.01.01,ON,False,NaN,-0.01,3.99
6362213,25291,12.091.809/...,3R PETROLEU...,annual,separate,2021-12-31,1,2021-01-01,2021-12-31,0,3.99.02.01,ON,False,NaN,-0.01,3.99

array(['f', 'f', 'f', ..., 'f', 'f', 'f'], dtype='<U1')