In [35]:
import importlib
import pandas as pd
import context # noqa
import brfinance.finance as bf
importlib.reload(bf)
pd.options.display.max_colwidth = 50
pd.options.display.max_rows = 40

In [36]:
# prio  22187 
# petro 9512
cia = bf.Finance(9512, report_type='consolidated', unit=1_000_000, first_period='2016-01-01')
cia

Selected first_period = 2016-01-01
Selected last_period = 2200-12-31

In [27]:
cia.info

{'CVM number': 9512,
 'Fiscal Code': '33.000.167/0001-01',
 'Name': 'PETROLEO BRASILEIRO S.A. PETROBRAS',
 'Annual Reports': ['2010-12-31',
  '2011-12-31',
  '2012-12-31',
  '2013-12-31',
  '2014-12-31',
  '2015-12-31',
  '2016-12-31',
  '2017-12-31',
  '2018-12-31',
  '2019-12-31',
  '2020-12-31',
  '2021-12-31'],
 'Last Quarterly Report': '2021-09-30'}

In [ ]:
cia.assets

In [ ]:
cia.show_accounts = 2
cia.assets

In [ ]:
cia.liabilities_and_equity

In [28]:
cia.income

,DS_CONTA,CD_CONTA,ST_CONTA_FIXA,2016-12-31,2017-12-31,2018-12-31,2019-12-31,2020-12-31,2021-12-31
0,Receita de Venda de Bens e/ou Serviços,3.01,True,282589.00,283695.00,310255.00,302245.00,272069.00,452668.00
1,Custo dos Bens e/ou Serviços Vendidos,3.02,True,-192611.00,-192100.00,-191568.00,-180140.00,-148107.00,-233031.00
2,Resultado Bruto,3.03,True,89978.00,91595.00,118687.00,122105.00,123962.00,219637.00
3,Despesas/Receitas Operacionais,3.04,True,-73496.00,-53822.00,-56222.00,-40404.00,-74341.00,-8806.00
4,Despesas com Vendas,3.04.01,True,-13825.00,-14510.00,-13938.00,-17746.00,-25020.00,-22806.00
5,Despesas Gerais e Administrativas,3.04.02,True,-11482.00,-9314.00,-8146.00,-8368.00,-5525.00,-6340.00
6,Outras Despesas Operacionais,3.04.05,True,-47560.00,-32147.00,-36058.00,-14837.00,-40524.00,11913.00
7,Tributárias,3.04.05.01,False,-2456.00,-5921.00,-2475.00,-2484.00,-4971.00,-2180.00
8,Custo com Pesquisa e Desenvolvimento Tecnológico,3.04.05.02,False,-1826.00,-1831.00,-2345.00,-2268.00,-1819.00,-3033.00
9,Custo Exploratório para Extração de Petróleo e...,3.04.05.03,False,-6056.00,-2563.00,-1904.00,-3197.00,-4170.00,-3731.00
10,Outras Despesas/Receitas Operacionais Líquidas,3.04.05.05,False,-16925.00,-17970.00,-21645.00,4742.00,4695.00,3967.00
11,Reversão/Perdas no valor de recuperação de ati...,3.04.05.07,False,-20297.00,-3862.00,-7689.00,-11630.00,-34259.00,16890.00
12,Resultado de Equivalência Patrimonial,3.04.06,True,-629.00,2149.00,1920.00,547.00,-3272.00,8427.00
13,Resultado Antes do Resultado Financeiro e dos ...,3.05,True,16482.00,37773.00,62465.00,81701.00,49621.00,210831.00
14,Resultado Financeiro,3.06,True,-27185.00,-31599.00,-23498.00,-34459.00,-49584.00,-59256.00
15,Receitas Financeiras,3.06.01,True,3638.00,3337.00,8713.00,5271.00,2821.00,4458.00
16,Receitas Financeiras,3.06.01.01,False,3638.00,3337.00,8713.00,5271.00,2821.00,4458.00
17,Despesas Financeiras,3.06.02,True,-30823.00,-34936.00,-32211.00,-39730.00,-52405.00,-63714.00
18,Despesas Financeiras,3.06.02.01,False,-24176.00,-23612.00,-20479.00,-27878.00,-31108.00,-27636.00
19,Variações Monetárias e Cambiais Líquidas,3.06.02.02,False,-6647.00,-11324.00,-11732.00,-11852.00,-21297.00,-36078.00
20,Resultado Antes dos Tributos sobre o Lucro,3.07,True,-10703.00,6174.00,38967.00,47242.00,37.00,151575.00
21,Imposto de Renda e Contribuição Social sobre o...,3.08,True,-2342.00,-5797.00,-15462.00,-16400.00,6209.00,-44311.00
22,Corrente,3.08.01,True,-5622.00,-4345.00,-14165.00,-5364.00,-2731.00,-22667.00
23,Diferido,3.08.02,True,3280.00,-1452.00,-1297.00,-11036.00,8940.00,-21644.00
24,Resultado Líquido das Operações Continuadas,3.09,True,-13045.00,377.00,23505.00,30842.00,6246.00,107264.00
25,Resultado Líquido de Operações Descontinuadas,3.10,True,NaN,NaN,3193.00,10128.00,NaN,NaN
26,Lucro/Prejuízo Líquido das Operações Descontin...,3.10.01,True,NaN,NaN,3193.00,10128.00,NaN,NaN
27,Lucro/Prejuízo Consolidado do Período,3.11,True,-13045.00,377.00,26698.00,40970.00,6246.00,107264.00
28,Atribuído a Sócios da Empresa Controladora,3.11.01,True,-14824.00,-446.00,25779.00,40137.00,7108.00,106668.00
29,Atribuído a Sócios Não Controladores,3.11.02,True,1779.00,823.00,919.00,833.00,-862.00,596.00
30,ON,3.99.01.01,False,-1.14,-0.03,1.98,3.08,0.54,8.18
31,PN,3.99.01.02,False,-1.14,-0.03,1.98,3.08,0.54,8.18
32,ON,3.99.02.01,False,-1.14,-0.03,1.98,3.08,0.54,8.18
33,PN,3.99.02.02,False,-1.14,-0.03,1.98,3.08,0.54,8.18

In [37]:
cia.operating_performance

,2016-12-31,2017-12-31,2018-12-31,2019-12-31,2020-12-31,2021-12-31
CD_CONTA,,,,,,
1,804945.000000,831515.000000,860473.000000,926011.000000,987419.000000,972951.000000
2.03,252743.000000,269609.000000,283543.000000,299137.000000,311150.000000,389581.000000
3.01,282589.000000,283695.000000,310255.000000,302245.000000,272069.000000,452668.000000
3.02,-192611.000000,-192100.000000,-191568.000000,-180140.000000,-148107.000000,-233031.000000
3.03,89978.000000,91595.000000,118687.000000,122105.000000,123962.000000,219637.000000
...,...,...,...,...,...,...
return_on_equity,-0.051614,0.001398,0.094159,0.136961,0.020074,0.275332
gross_margin,0.318406,0.322864,0.382547,0.403993,0.455627,0.485205
ebit_margin,0.058325,0.133147,0.201334,0.270314,0.182384,0.465752
operating_margin,0.228852,0.238887,0.311366,0.317593,0.343358,0.420818
net_margin,-0.046162,0.001329,0.086052,0.135552,0.022957,0.236960

In [ ]:
cia.earnings_per_share

In [ ]:
cia.show_accounts = 1
cia.income

In [ ]:
cia.cash_flow

In [ ]:
cia.valuation

In [ ]:
lista = [3,10,1]
lista.sort()
lista