In [28]:
import importlib
import pandas as pd
import numpy as np
import company as co
# from company import Company
importlib.reload(co)

pd.options.display.max_colwidth = 20
pd.options.display.max_rows = 40

In [29]:
petro = co.Company(9512)
df = petro.assets
df

,DS_CONTA,CD_CONTA,ST_CONTA_FIXA,2009-12-31,2010-12-31,2011-12-31,2012-12-31,2013-12-31,2014-12-31,2015-12-31,2016-12-31,2017-12-31,2018-12-31,2019-12-31,2020-12-31,2021-09-30
0,Ativo Total,1,True,3.504189e+11,5.168457e+11,6.000970e+11,6.690316e+11,7.529670e+11,7.933750e+11,9.001350e+11,8.049450e+11,8.315150e+11,8.604730e+11,9.260110e+11,9.874190e+11,9.746890e+11
1,Ativo Circulante,1.01,True,7.437357e+10,1.059022e+11,1.211637e+11,1.181018e+11,1.233510e+11,1.350230e+11,1.686070e+11,1.459070e+11,1.559090e+11,1.436060e+11,1.121010e+11,1.423230e+11,1.663340e+11
2,Caixa e Equivale...,1.01.01,True,2.903423e+10,2.941619e+10,3.574724e+10,2.762800e+10,3.717200e+10,4.423900e+10,9.784500e+10,6.910800e+10,7.449400e+10,5.385400e+10,2.971400e+10,6.085600e+10,5.939400e+10
3,Caixa e Bancos,1.01.01.01,False,2.853964e+09,3.293879e+09,3.731249e+09,2.024301e+09,2.227292e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aplicações Finan...,1.01.01.02,False,2.618026e+10,2.612231e+10,3.201599e+10,2.560370e+10,3.494453e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,Intangível,1.02.04,True,8.270864e+09,8.153873e+10,8.143361e+10,8.120676e+10,3.612100e+10,1.197600e+10,1.207200e+10,1.066300e+10,7.740000e+09,1.087000e+10,7.848900e+10,7.767800e+10,1.660100e+10
83,Intangíveis,1.02.04.01,True,7.346025e+09,8.063279e+10,8.048451e+10,8.026607e+10,3.518388e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Direitos e Conce...,1.02.04.01.02,False,5.606748e+09,7.895228e+10,7.880350e+10,7.870176e+10,3.368941e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,Softwares,1.02.04.01.03,False,1.739277e+09,1.680513e+09,1.681011e+09,1.564311e+09,1.494470e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,Goodwill,1.02.04.02,True,9.248390e+08,9.059360e+08,9.491000e+08,9.406830e+08,9.373180e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DS_CONTA       87 non-null     object
 1   CD_CONTA       87 non-null     object
 2   ST_CONTA_FIXA  87 non-null     bool
 3   2009-12-31     61 non-null     float64
 4   2010-12-31     62 non-null     float64
 5   2011-12-31     63 non-null     float64
 6   2012-12-31     64 non-null     float64
 7   2013-12-31     65 non-null     float64
 8   2014-12-31     30 non-null     float64
 9   2015-12-31     30 non-null     float64
 10  2016-12-31     29 non-null     float64
 11  2017-12-31     38 non-null     float64
 12  2018-12-31     29 non-null     float64
 13  2019-12-31     28 non-null     float64
 14  2020-12-31     27 non-null     float64
 15  2021-09-30     27 non-null     float64
dtypes: bool(1), float64(13), object(2)
memory usage: 10.4+ KB

In [31]:
df = petro.liabilities_and_equity
df

,DS_CONTA,CD_CONTA,ST_CONTA_FIXA,2009-12-31,2010-12-31,2011-12-31,2012-12-31,2013-12-31,2014-12-31,2015-12-31,2016-12-31,2017-12-31,2018-12-31,2019-12-31,2020-12-31,2021-09-30
0,Passivo Total,2,True,3.504189e+11,5.168457e+11,6.000970e+11,6.690316e+11,7.529670e+11,7.933750e+11,9.001350e+11,8.049450e+11,8.315150e+11,8.604730e+11,9.260110e+11,9.874190e+11,9.746890e+11
1,Passivo Circulante,2.01,True,5.516193e+10,5.594763e+10,6.821233e+10,6.962058e+10,8.252500e+10,8.265900e+10,1.115720e+11,8.116700e+10,8.253500e+10,9.706800e+10,1.161470e+11,1.362870e+11,1.386640e+11
2,Obrigações Socia...,2.01.01,True,2.303943e+09,2.551065e+09,4.742206e+09,4.420579e+09,4.806000e+09,5.489000e+09,5.085000e+09,7.159000e+09,4.331000e+09,6.426000e+09,6.632000e+09,1.015000e+10,9.182000e+09
3,Obrigações Sociais,2.01.01.01,True,3.244340e+08,4.202850e+08,4.364810e+08,7.610600e+08,6.974300e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Obrigações Traba...,2.01.01.02,True,1.979509e+09,2.130780e+09,4.305725e+09,3.659519e+09,4.108691e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,Lucros/Prejuízos...,2.03.05,True,-1.247335e+09,NaN,NaN,-1.541320e+08,NaN,-2.157700e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,Ajustes de Avali...,2.03.06,True,9.652600e+07,2.870840e+08,3.457000e+08,-1.445363e+10,-1.243954e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Ajustes Acumulad...,2.03.07,True,-1.633470e+08,-1.964790e+08,9.266850e+08,2.077909e+09,5.195931e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,Outros Resultado...,2.03.08,True,NaN,NaN,NaN,NaN,-7.244000e+09,-2.337600e+10,-4.333400e+10,-3.403700e+10,-2.126800e+10,-2.602900e+10,-3.716900e+10,-2.698300e+10,-2.110000e+08
86,Participação dos...,2.03.09,True,2.576659e+09,3.063093e+09,2.384730e+09,2.353980e+09,1.394000e+09,1.874000e+09,3.199000e+09,2.513000e+09,5.624000e+09,6.318000e+09,3.596000e+09,2.740000e+09,6.612000e+09

In [32]:
df.sort_values('DS_CONTA').tail(10)

,DS_CONTA,CD_CONTA,ST_CONTA_FIXA,2009-12-31,2010-12-31,2011-12-31,2012-12-31,2013-12-31,2014-12-31,2015-12-31,2016-12-31,2017-12-31,2018-12-31,2019-12-31,2020-12-31,2021-09-30
63,Provisões Previd...,2.02.04.01.02,True,1.017680e+08,1.926030e+08,2.904220e+08,6.867150e+08,1.331701e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Provisões para O...,2.02.04.01.05,False,NaN,1.079410e+08,7.917170e+08,1.524410e+08,8.914100e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,Reserva Estatutária,2.03.04.02,True,1.294209e+09,1.421619e+09,2.448518e+09,3.475478e+09,4.502533e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,Reserva Legal,2.03.04.01,True,1.090166e+10,1.265348e+10,1.430852e+10,1.535326e+10,1.652364e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,Reserva de Incen...,2.03.02.08,False,5.148570e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,Reserva de Incen...,2.03.04.07,True,1.111632e+09,1.346681e+09,1.405132e+09,1.411493e+09,1.413779e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,Reserva de Reten...,2.03.04.05,True,7.141905e+10,8.590195e+10,1.044620e+11,1.146886e+11,1.265958e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,Reservas de Capital,2.03.02,True,1.937392e+09,-6.257000e+06,5.626430e+08,6.302880e+08,7.370000e+08,-6.460000e+08,2.100000e+07,1.035000e+09,2.457000e+09,2.458000e+09,2.449000e+09,2.449000e+09,-1.254000e+09
77,Reservas de Lucros,2.03.04,True,8.472655e+10,1.013237e+11,1.226241e+11,1.349288e+11,1.490360e+11,1.274380e+11,9.261200e+10,7.780000e+10,7.736400e+10,9.536400e+10,1.248290e+11,1.275120e+11,1.651100e+11
56,Tributos Diferidos,2.02.03,True,2.045778e+10,2.589836e+10,3.322977e+10,2.447220e+10,2.320600e+10,8.052000e+09,9.060000e+08,8.560000e+08,3.956000e+09,2.536000e+09,7.095000e+09,1.015000e+09,8.450000e+08

In [33]:
petro.equity

,DS_CONTA,CD_CONTA,ST_CONTA_FIXA,2009-12-31,2010-12-31,2011-12-31,2012-12-31,2013-12-31,2014-12-31,2015-12-31,2016-12-31,2017-12-31,2018-12-31,2019-12-31,2020-12-31,2021-09-30
0,Patrimônio Líqui...,2.03,True,1.668931e+11,3.098283e+11,3.322236e+11,3.307754e+11,3.493340e+11,3.107220e+11,2.579300e+11,2.527430e+11,2.696090e+11,2.835430e+11,2.991370e+11,3.111500e+11,3.756890e+11
1,Capital Social R...,2.03.01,True,7.896669e+10,2.053571e+11,2.053797e+11,2.053921e+11,2.054110e+11,2.054320e+11,2.054320e+11,2.054320e+11,2.054320e+11,2.054320e+11,2.054320e+11,2.054320e+11,2.054320e+11
2,Reservas de Capital,2.03.02,True,1.937392e+09,-6.257000e+06,5.626430e+08,6.302880e+08,7.370000e+08,-6.460000e+08,2.100000e+07,1.035000e+09,2.457000e+09,2.458000e+09,2.449000e+09,2.449000e+09,-1.254000e+09
3,Contribuição Adi...,2.03.02.07,False,1.422535e+09,-6.257000e+06,5.626430e+08,6.302880e+08,7.368850e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Reserva de Incen...,2.03.02.08,False,5.148570e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Reservas de Lucros,2.03.04,True,8.472655e+10,1.013237e+11,1.226241e+11,1.349288e+11,1.490360e+11,1.274380e+11,9.261200e+10,7.780000e+10,7.736400e+10,9.536400e+10,1.248290e+11,1.275120e+11,1.651100e+11
6,Reserva Legal,2.03.04.01,True,1.090166e+10,1.265348e+10,1.430852e+10,1.535326e+10,1.652364e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Reserva Estatutária,2.03.04.02,True,1.294209e+09,1.421619e+09,2.448518e+09,3.475478e+09,4.502533e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Reserva de Reten...,2.03.04.05,True,7.141905e+10,8.590195e+10,1.044620e+11,1.146886e+11,1.265958e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Reserva de Incen...,2.03.04.07,True,1.111632e+09,1.346681e+09,1.405132e+09,1.411493e+09,1.413779e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Lucros/Prejuízos...,2.03.05,True,-1.247335e+09,NaN,NaN,-1.541320e+08,NaN,-2.157700e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Ajustes de Avali...,2.03.06,True,9.652600e+07,2.870840e+08,3.457000e+08,-1.445363e+10,-1.243954e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Ajustes Acumulad...,2.03.07,True,-1.633470e+08,-1.964790e+08,9.266850e+08,2.077909e+09,5.195931e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Outros Resultado...,2.03.08,True,NaN,NaN,NaN,NaN,-7.244000e+09,-2.337600e+10,-4.333400e+10,-3.403700e+10,-2.126800e+10,-2.602900e+10,-3.716900e+10,-2.698300e+10,-2.110000e+08
14,Participação dos...,2.03.09,True,2.576659e+09,3.063093e+09,2.384730e+09,2.353980e+09,1.394000e+09,1.874000e+09,3.199000e+09,2.513000e+09,5.624000e+09,6.318000e+09,3.596000e+09,2.740000e+09,6.612000e+09

In [ ]:
for column, c_type in zip(df.columns, df.dtypes):
    if (c_type != 'int8') and (c_type != 'bool') and (c_type != 'float64'):
        print(column, c_type)
        df[f'{column}'] = df[f'{column}'].astype('category')